---
title: "Changing PDF Orientation"
author: "Gabby Novak"
date: 2019-10-13
categories: ["PDFs"]
tags: ["LaTeX"]
---

```{r setup, include=F}
knitr::opts_chunk$set(collapse = TRUE, 
                      fig.height=3, 
                      fig.width=3,
                      message=F,
                      warning=F,
                      error=F,
                      fig.align="center")
```

# Changing the orientation for the whole document

PDFs knit in a portrait orientation by default. However, should you want to output a PDF in landscape mode, it has to be specified in the LaTeX arguments in the YAML header.

```
---
title: "Landscape PDF"
subtitle: "This demonstrates a landscape PDF output"
output: pdf_document
classoption: landscape
---
This document is 8.5 inches tall and 11 inches wide.
```

** The code above produces [this output]("https://github.com/ganovak/R4Humans-AuxFiles/blob/master/ChangingPDFOrientation/Landscape.pdf")**

# Changing the orientation for specific pages

Sometimes, you have a report with graphics that would be better displayed in landscape mode but overall, you'd like the document to be in standard portrait mode. To accomplish this, you will need to use the LaTeX package `pdflscape` and use the following code in your YAML header.

```
---
title: "Variable Orientation"
subtitle: "This demonstrates a variable orientation PDF output"
output: 
  pdf_document:
header-includes:
- \usepackage{pdflscape}
---
```

Anything you would like in portrait mode, encase in `\begin{landscape}` and `\end{landscape}` commands. Anything not between these two calls will be the default portrait mode.

** Example output can be found [here]("https://github.com/ganovak/R4Humans-AuxFiles/blob/master/ChangingPDFOrientation/VariableOrientation.pdf") **
